### ISSUE TITLE
Upgrade to latest version of `knack` package

### ISSUE THREAD

**Issue by samedder** [Microsoft/service-fabric-cli#73]
Right now the version of `knack` is fixed. Updating to the latest version should be done automatically.

- sfctl version 4.0.0

**Comment by Christina-Kang** [comment]
@samedder This may create some issues, as per this from the knack documentation:

"The project is in initial development phase . We recommend pinning to at least a specific minor version when marking knack as a dependency in your project."

**Comment by samedder** [comment]
@IgnatiusFlo if you'd like to work on it you're more than welcome to.

**Comment by Christina-Kang** [comment]
Closing the issue since knack is not backwards compatible between versions, and may introduce breaking changes since it is still in the initial development stage. Similarly, sfctl will soon take a dependency on a change specific to a patch rather than a minor version, so setting a specified version is the best course of action until version 1.0.0 is released.
